Changed all instances of Pano to Sphere
AerialSphere/xp360-api-samples pull request #10
Opened 2023-11-10 00:08 UTC by Dumamax

There are a few minor fixes to the code as well, but the "major" changes will come in another commit

2023-11-10 22:41 UTC, bobsbeenjamin requested changes

2023-11-10 22:41 UTC, bobsbeenjamin commented on 11-look-at/demo.js
I'm trusting that your number changes here look in the correct directions. The numbers are believable, at least.

2023-11-10 22:41 UTC, bobsbeenjamin commented on 27-set-pano-marker-distance/demo.details
> +description: Sets the max distance at which to render sphere (panorama) markers
We can probably eliminate sphere, and just say `render markers`

2023-11-10 22:41 UTC, bobsbeenjamin commented on 34-set-fov-range/demo.js
> +    fovMax = document.getElementById('fovMax');
It looks like you were trying to line up function names (`setFovMin` and `setFovMax`) with functionality. But it still reads as reversed (ie, min acts on max, and vice versa). Maybe just change the function names themselves, and then make sure they get called correctly?

2023-11-13 17:20 UTC, Dumamax commented on 27-set-pano-marker-distance/demo.details
> +description: Sets the max distance at which to render sphere (panorama) markers
This is only for rendering sphere markers though, so I could see it being confusing to state "Sets the max distance at which to render markers"

2023-11-13 17:28 UTC, Dumamax commented on 34-set-fov-range/demo.js
> +    fovMax = document.getElementById('fovMax');
Well the only things I changed were the typos: foxMin & foxMax -> fovMin & fovMax, so I'm not entirely sure what you're meaning by this, but I will go back in and see if I can change some things around to fix it

2023-11-13 17:38 UTC, Dumamax reviewed
Except for the "setFovMin/Max" issue, everything else seems good, and comments have been responded to

2023-11-13 17:38 UTC, Dumamax commented on 34-set-fov-range/demo.js
> +    fovMax = document.getElementById('fovMax');
I went back and looked through it again, and I'm not sure I see any issues with the code. I think it'll work as expected, but if I'm missing something, definitely let me know. @bobsbeenjamin

2023-11-13 19:23 UTC, bobsbeenjamin commented on 27-set-pano-marker-distance/demo.details
> +description: Sets the max distance at which to render sphere (panorama) markers
Yes. You are right. I guess my real issue is with leaving `panorama` in the verbiage. I thing that threw me off.

2023-11-13 19:26 UTC, bobsbeenjamin commented on 34-set-fov-range/demo.js
> +    fovMax = document.getElementById('fovMax');
Fixing the typo is better than not fixing it, so I'll approve this either way.
But it should be noted that your fix exposed a pre-existing issue: We define a function called `setFovMin` (on line 36), then immediately start dealing with `fovMax` (not min) on the first statement in the function (line 37).

2023-11-13 19:40 UTC, Dumamax commented on 34-set-fov-range/demo.js
> +    fovMax = document.getElementById('fovMax');
Ahh, I see what you mean. I think the confusing part with this is that both setFovMin and setFovMax are doing essentially the same thing, they are both using setFovRange(fovMin, fovMax). Both are just setting the min AND the max. I'll switch this up so it just sets the min, and just sets the max for the appropriate functions

2023-12-05 19:16 UTC, bobsbeenjamin approved these changes
Pushing this through

2023-12-05 19:17 UTC, merged